'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace BravoOrders
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ProcessOrdersSoap", [Namespace]:="urn:schemas-bravocorp-com.namespaces.event.simple")>  _
    Public Class ProcessOrders
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/BravoOrdersWS/orderWS.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:schemas-bravocorp-com.namespaces.event.simple/SubmitNewOrder", RequestNamespace:="urn:schemas-bravocorp-com.namespaces.event.simple", ResponseNamespace:="urn:schemas-bravocorp-com.namespaces.event.simple", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SubmitNewOrder(ByVal strXML As String) As String
            Dim results() As Object = Me.Invoke("SubmitNewOrder", New Object() {strXML})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginSubmitNewOrder(ByVal strXML As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SubmitNewOrder", New Object() {strXML}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSubmitNewOrder(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
    End Class
End Namespace
