'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace TMW
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimeManagerWebSoap", [Namespace]:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(System.Object()))>  _
    Public Class TimeManagerWeb
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://localhost/TimeManagerWeb/TimeManagerWeb.asmx"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/SaveHourObj", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveHourObj(ByVal obj As tmHours) As Boolean
            Dim results() As Object = Me.Invoke("SaveHourObj", New Object() {obj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginSaveHourObj(ByVal obj As tmHours, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveHourObj", New Object() {obj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSaveHourObj(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/SaveHourArrayList", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SaveHourArrayList(ByVal userId As String, ByVal startDate As Date, ByVal endDate As Date, ByVal objCol() As Object) As Boolean
            Dim results() As Object = Me.Invoke("SaveHourArrayList", New Object() {userId, startDate, endDate, objCol})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginSaveHourArrayList(ByVal userId As String, ByVal startDate As Date, ByVal endDate As Date, ByVal objCol() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("SaveHourArrayList", New Object() {userId, startDate, endDate, objCol}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndSaveHourArrayList(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/TestConnection", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestConnection() As String
            Dim results() As Object = Me.Invoke("TestConnection", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        Public Function BeginTestConnection(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("TestConnection", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndTestConnection(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/Login", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Login(ByVal userId As String, ByVal password As String) As tmUser
            Dim results() As Object = Me.Invoke("Login", New Object() {userId, password})
            Return CType(results(0),tmUser)
        End Function
        
        '<remarks/>
        Public Function BeginLogin(ByVal userId As String, ByVal password As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("Login", New Object() {userId, password}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndLogin(ByVal asyncResult As System.IAsyncResult) As tmUser
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),tmUser)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/GetAllProjects", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllProjects() As Project()
            Dim results() As Object = Me.Invoke("GetAllProjects", New Object(-1) {})
            Return CType(results(0),Project())
        End Function
        
        '<remarks/>
        Public Function BeginGetAllProjects(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllProjects", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAllProjects(ByVal asyncResult As System.IAsyncResult) As Project()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Project())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/AddProject", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddProject(ByRef ProjectObj As Project) As Boolean
            Dim results() As Object = Me.Invoke("AddProject", New Object() {ProjectObj})
            ProjectObj = CType(results(1),Project)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginAddProject(ByVal ProjectObj As Project, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddProject", New Object() {ProjectObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddProject(ByVal asyncResult As System.IAsyncResult, ByRef ProjectObj As Project) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            ProjectObj = CType(results(1),Project)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/GetAllUsers", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetAllUsers() As tmUser()
            Dim results() As Object = Me.Invoke("GetAllUsers", New Object(-1) {})
            Return CType(results(0),tmUser())
        End Function
        
        '<remarks/>
        Public Function BeginGetAllUsers(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetAllUsers", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetAllUsers(ByVal asyncResult As System.IAsyncResult) As tmUser()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),tmUser())
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/AddUser", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AddUser(ByVal userObj As tmUser) As Boolean
            Dim results() As Object = Me.Invoke("AddUser", New Object() {userObj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginAddUser(ByVal userObj As tmUser, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("AddUser", New Object() {userObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndAddUser(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/UpdateUser", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateUser(ByVal originalUserId As String, ByVal userObj As tmUser) As Boolean
            Dim results() As Object = Me.Invoke("UpdateUser", New Object() {originalUserId, userObj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateUser(ByVal originalUserId As String, ByVal userObj As tmUser, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateUser", New Object() {originalUserId, userObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateUser(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/DeleteUser", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteUser(ByVal userObj As tmUser) As Boolean
            Dim results() As Object = Me.Invoke("DeleteUser", New Object() {userObj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginDeleteUser(ByVal userObj As tmUser, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteUser", New Object() {userObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDeleteUser(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/DeleteProject", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DeleteProject(ByVal ProjectObj As Project) As Boolean
            Dim results() As Object = Me.Invoke("DeleteProject", New Object() {ProjectObj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginDeleteProject(ByVal ProjectObj As Project, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("DeleteProject", New Object() {ProjectObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndDeleteProject(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/UpdateProject", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UpdateProject(ByVal OriginalProjectName As String, ByVal ProjectObj As Project) As Boolean
            Dim results() As Object = Me.Invoke("UpdateProject", New Object() {OriginalProjectName, ProjectObj})
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        Public Function BeginUpdateProject(ByVal OriginalProjectName As String, ByVal ProjectObj As Project, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("UpdateProject", New Object() {OriginalProjectName, ProjectObj}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndUpdateProject(ByVal asyncResult As System.IAsyncResult) As Boolean
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),Boolean)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimeManagerWeb/TimeManagerWeb/GetProjectReportInfoByEmployee", RequestNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", ResponseNamespace:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetProjectReportInfoByEmployee(ByVal userId As String, ByVal StartDate As Date, ByVal EndDate As Date) As tmHours()
            Dim results() As Object = Me.Invoke("GetProjectReportInfoByEmployee", New Object() {userId, StartDate, EndDate})
            Return CType(results(0),tmHours())
        End Function
        
        '<remarks/>
        Public Function BeginGetProjectReportInfoByEmployee(ByVal userId As String, ByVal StartDate As Date, ByVal EndDate As Date, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetProjectReportInfoByEmployee", New Object() {userId, StartDate, EndDate}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndGetProjectReportInfoByEmployee(ByVal asyncResult As System.IAsyncResult) As tmHours()
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),tmHours())
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb")>  _
    Public Class tmHours
        
        '<remarks/>
        Public ProjectName As String
        
        '<remarks/>
        Public userId As String
        
        '<remarks/>
        Public hours As Single
        
        '<remarks/>
        Public startDate As Date
        
        '<remarks/>
        Public endDate As Date
        
        '<remarks/>
        Public description As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb")>  _
    Public Class Project
        
        '<remarks/>
        Public ProjectName As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/TimeManagerWeb/TimeManagerWeb")>  _
    Public Class tmUser
        
        '<remarks/>
        Public userId As String
        
        '<remarks/>
        Public password As String
        
        '<remarks/>
        Public nameLast As String
        
        '<remarks/>
        Public nameFirst As String
        
        '<remarks/>
        Public admin As Boolean
    End Class
End Namespace
